tools:
    shell:
        allow:
            - find *
            - head *
            - grep *
            - wc *
            - echo *
            - cat *
            - cd *
            - python3 *
            - sed *
            - ls *
            - mkdir *
            - npx tsc *
            - tail *
            - npx eslint *
            - git diff *
            - which kaggle
            - lsof *
            - xargs *
            - npx tsx *
            - sleep 5
            - curl *
            - sleep 3000
            - seq 1 *
            - '[ "$STATUS" *'
            - break
            - sleep 150
            - sleep 15
            - sleep 30
            - sleep 60
            - ps aux
            - kaggle kernels status *
            - sleep 3
            - sleep 45
            - sleep 90
            - sleep 10
            - sleep 120
            - sleep 8
            - npx vitest *
            - npx ts-prune *
            - file *
            - git ls-files *
            - git status *
            - rm *
            - "true"
            - awk *
