/**
 * API Metadata - Configuration for all supported APIs
 * Includes registration links, descriptions, and required credentials
 */

export interface ApiConfig {
  id: string;
  name: string;
  category: string;
  description: string;
  registrationUrl: string;
  docsUrl: string;
  envKey?: string;
  envKeys?: string[]; // For APIs requiring multiple keys
  free: boolean;
  rateLimit: string;
  status: 'public' | 'authenticated' | 'premium';
}

export const API_METADATA: ApiConfig[] = [
  // SATELLITE & IMAGERY
  {
    id: 'cesium_ion',
    name: 'Cesium Ion',
    category: 'Satellite & Imagery',
    description: '3D globe, terrain, and imagery layers',
    registrationUrl: 'https://ion.cesium.com/signup',
    docsUrl: 'https://cesium.com/learn/',
    envKey: 'CESIUM_ION_ACCESS_TOKEN',
    free: true,
    rateLimit: 'Unlimited (free tier)',
    status: 'authenticated',
  },
  {
    id: 'sentinel_hub',
    name: 'Sentinel Hub',
    category: 'Satellite & Imagery',
    description: 'ESA Sentinel-2 satellite imagery and analytics',
    registrationUrl: 'https://www.sentinel-hub.com/create_account/',
    docsUrl: 'https://www.sentinel-hub.com/develop/',
    envKeys: ['SENTINEL_HUB_CLIENT_ID', 'SENTINEL_HUB_CLIENT_SECRET'],
    free: true,
    rateLimit: '30 days free trial',
    status: 'authenticated',
  },
  {
    id: 'nasa_firms',
    name: 'NASA FIRMS',
    category: 'Satellite & Imagery',
    description: 'Wildfire detection (MODIS/VIIRS)',
    registrationUrl: 'https://firms.modaps.eosdis.nasa.gov/api/',
    docsUrl: 'https://firms.modaps.eosdis.nasa.gov/mapserver/',
    envKey: 'NASA_FIRMS_MAP_KEY',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },
  {
    id: 'planet',
    name: 'Planet Labs',
    category: 'Satellite & Imagery',
    description: 'High-resolution satellite imagery',
    registrationUrl: 'https://www.planet.com/',
    docsUrl: 'https://developers.planet.com/',
    envKey: 'PLANET_API_KEY',
    free: false,
    rateLimit: 'Usage-based',
    status: 'premium',
  },

  // AVIATION
  {
    id: 'opensky',
    name: 'OpenSky Network',
    category: 'Aviation',
    description: 'Live flight tracking and historical data',
    registrationUrl: 'https://opensky-network.org/community/',
    docsUrl: 'https://opensky-network.org/apidoc/rest.html',
    envKeys: ['OPENSKY_CLIENT_ID', 'OPENSKY_CLIENT_SECRET'],
    free: true,
    rateLimit: '400 req/hr (free), unlimited (premium)',
    status: 'authenticated',
  },
  {
    id: 'adsb_lol',
    name: 'ADSB.lol',
    category: 'Aviation',
    description: 'Public real-time aircraft tracking feed',
    registrationUrl: 'https://adsb.lol/',
    docsUrl: 'https://adsb.lol/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },
  {
    id: 'adsb_fi',
    name: 'adsb.fi',
    category: 'Aviation',
    description: 'Public real-time aircraft tracking feed',
    registrationUrl: 'https://adsb.fi/',
    docsUrl: 'https://adsb.fi/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },
  {
    id: 'airlabs',
    name: 'AirLabs API',
    category: 'Aviation',
    description: 'Real-time flight data API',
    registrationUrl: 'https://airlabs.co/',
    docsUrl: 'https://airlabs.co/',
    envKey: 'AIRLABS_API_KEY',
    free: true,
    rateLimit: 'Free tier available',
    status: 'authenticated',
  },
  {
    id: 'openflights',
    name: 'OpenFlights',
    category: 'Aviation',
    description: 'Open database of airline routes and airports',
    registrationUrl: 'https://openflights.org/',
    docsUrl: 'https://openflights.org/data.html',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public dataset',
    status: 'public',
  },
  {
    id: 'wovodat',
    name: 'WOVOdat',
    category: 'Aviation',
    description: 'World Organization of Volcano Observatories database',
    registrationUrl: 'https://www.wovodat.org/',
    docsUrl: 'https://www.wovodat.org/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },
  {
    id: 'vaac_tokyo',
    name: 'Tokyo VAAC',
    category: 'Aviation',
    description: 'Tokyo Volcanic Ash Advisory Center',
    registrationUrl: 'https://ds.data.jma.go.jp/svd/vaac/data/',
    docsUrl: 'https://ds.data.jma.go.jp/svd/vaac/data/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public data',
    status: 'public',
  },
  {
    id: 'vaac_anchorage',
    name: 'Anchorage VAAC',
    category: 'Aviation',
    description: 'Anchorage Volcanic Ash Advisory Center',
    registrationUrl: 'https://www.weather.gov/vaac/',
    docsUrl: 'https://www.weather.gov/vaac/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public data',
    status: 'public',
  },
  {
    id: 'vaac_washington',
    name: 'Washington VAAC',
    category: 'Aviation',
    description: 'Washington Volcanic Ash Advisory Center',
    registrationUrl: 'https://www.nhc.noaa.gov/',
    docsUrl: 'https://www.nhc.noaa.gov/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public data',
    status: 'public',
  },
  {
    id: 'nasa_so2',
    name: 'NASA SO2 Monitoring',
    category: 'Aviation',
    description: 'NASA satellite sulfur dioxide monitoring',
    registrationUrl: 'https://so2.gsfc.nasa.gov/',
    docsUrl: 'https://so2.gsfc.nasa.gov/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public data',
    status: 'public',
  },
  {
    id: 'noaa_so2',
    name: 'NOAA SO2 Portal',
    category: 'Aviation',
    description: 'NOAA sulfur dioxide monitoring portal',
    registrationUrl: 'https://satepsanone.nesdis.noaa.gov/pub/OMI/OMISO2/',
    docsUrl: 'https://satepsanone.nesdis.noaa.gov/pub/OMI/OMISO2/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public data',
    status: 'public',
  },
  {
    id: 'volcano_discovery',
    name: 'Volcano Discovery',
    category: 'Aviation',
    description: 'Real-time volcanic activity reports',
    registrationUrl: 'https://www.volcanodiscovery.com/',
    docsUrl: 'https://www.volcanodiscovery.com/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public data',
    status: 'public',
  },

  // MARITIME
  {
    id: 'aisstream',
    name: 'AISStream',
    category: 'Maritime',
    description: 'Real-time vessel tracking via AIS',
    registrationUrl: 'https://aisstream.io/',
    docsUrl: 'https://aisstream.io/documentation',
    envKey: 'AIS_STREAM_API_KEY',
    free: true,
    rateLimit: 'Free trial, then paid',
    status: 'authenticated',
  },
  {
    id: 'marine_traffic',
    name: 'MarineTraffic',
    category: 'Maritime',
    description: 'Alternative vessel tracking service',
    registrationUrl: 'https://www.marinetraffic.com/en/ais-api-services',
    docsUrl: 'https://www.marinetraffic.com/en/ais-api-services',
    envKey: 'MARINE_TRAFFIC_API_KEY',
    free: false,
    rateLimit: 'Paid subscription',
    status: 'premium',
  },

  // WEATHER & DISASTER (mostly public)
  {
    id: 'usgs_earthquakes',
    name: 'USGS Earthquakes',
    category: 'Weather & Disaster',
    description: 'Real-time earthquake data (no auth required)',
    registrationUrl: 'https://earthquake.usgs.gov/fdsnws/event/1/',
    docsUrl: 'https://earthquake.usgs.gov/fdsnws/event/1/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },
  {
    id: 'nasa_eonet',
    name: 'NASA EONET',
    category: 'Weather & Disaster',
    description: 'Natural events tracking (no auth required)',
    registrationUrl: 'https://eonet.gsfc.nasa.gov/api/v3/',
    docsUrl: 'https://eonet.gsfc.nasa.gov/api/v3/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },
  {
    id: 'gdacs',
    name: 'GDACS',
    category: 'Weather & Disaster',
    description: 'Global Disaster Alerts (no auth required)',
    registrationUrl: 'https://www.gdacs.org/',
    docsUrl: 'https://www.gdacs.org/xml/rss.xml',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public RSS',
    status: 'public',
  },
  {
    id: 'nws_alerts',
    name: 'NWS Alerts',
    category: 'Weather & Disaster',
    description: 'National Weather Service alerts (US only, no auth)',
    registrationUrl: 'https://api.weather.gov/',
    docsUrl: 'https://api.weather.gov/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },
  {
    id: 'noaa_space',
    name: 'NOAA Space Weather',
    category: 'Weather & Disaster',
    description: 'Solar storms & Kp Index (no auth required)',
    registrationUrl: 'https://services.swpc.noaa.gov/',
    docsUrl: 'https://services.swpc.noaa.gov/products/',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },

  // AI & ANALYTICS
  {
    id: 'google_gemini',
    name: 'Google Gemini',
    category: 'AI & Analytics',
    description: 'AI analysis of events and alerts',
    registrationUrl: 'https://ai.google.dev/',
    docsUrl: 'https://ai.google.dev/tutorials',
    envKey: 'GOOGLE_GEMINI_API_KEY',
    free: true,
    rateLimit: '60 req/min (free)',
    status: 'authenticated',
  },
  {
    id: 'anthropic_claude',
    name: 'Anthropic Claude',
    category: 'AI & Analytics',
    description: 'Alternative AI for event analysis',
    registrationUrl: 'https://console.anthropic.com/',
    docsUrl: 'https://docs.anthropic.com/',
    envKey: 'ANTHROPIC_API_KEY',
    free: false,
    rateLimit: 'Pay-as-you-go',
    status: 'premium',
  },

  // SOCIAL & NEWS
  {
    id: 'twitter_api',
    name: 'Twitter/X API',
    category: 'Social & News',
    description: 'Real-time tweets about disasters',
    registrationUrl: 'https://developer.twitter.com/',
    docsUrl: 'https://developer.twitter.com/en/docs/twitter-api',
    envKeys: ['TWITTER_API_KEY', 'TWITTER_API_SECRET', 'TWITTER_BEARER_TOKEN'],
    free: true,
    rateLimit: 'v2 Essential (free)',
    status: 'authenticated',
  },
  {
    id: 'newsapi',
    name: 'NewsAPI',
    category: 'Social & News',
    description: 'News aggregation and search',
    registrationUrl: 'https://newsapi.org/',
    docsUrl: 'https://newsapi.org/docs',
    envKey: 'NEWS_API_KEY',
    free: true,
    rateLimit: '100 req/day (free)',
    status: 'authenticated',
  },

  // CAMERAS
  {
    id: 'opencctv',
    name: 'OpenCCTV',
    category: 'Cameras',
    description: 'Public camera network (no auth)',
    registrationUrl: 'https://opencctv.org/',
    docsUrl: 'https://opencctv.org/api',
    envKey: 'N/A',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },

  // ADDITIONAL AVIATION
  {
    id: 'aviationstack',
    name: 'AviationStack',
    category: 'Aviation',
    description: 'Flight data, airport operations, carrier schedules',
    registrationUrl: 'https://aviationstack.com/',
    docsUrl: 'https://aviationstack.com/documentation',
    envKey: 'AVIATIONSTACK_API',
    free: true,
    rateLimit: 'Free tier: 100 req/mo',
    status: 'authenticated',
  },
  {
    id: 'icao',
    name: 'ICAO API',
    category: 'Aviation',
    description: 'NOTAM airport closures and aeronautical information',
    registrationUrl: 'https://applications.icao.int/',
    docsUrl: 'https://applications.icao.int/',
    envKey: 'ICAO_API_KEY',
    free: false,
    rateLimit: 'Paid subscription',
    status: 'premium',
  },
  {
    id: 'travelpayouts',
    name: 'Travelpayouts',
    category: 'Aviation',
    description: 'Flight price search and booking data',
    registrationUrl: 'https://www.travelpayouts.com/',
    docsUrl: 'https://www.travelpayouts.com/developers',
    envKey: 'TRAVELPAYOUTS_API_TOKEN',
    free: true,
    rateLimit: 'Free tier available',
    status: 'authenticated',
  },
  {
    id: 'wingbits',
    name: 'Wingbits',
    category: 'Aviation',
    description: 'Aircraft enrichment (owner, operator, type)',
    registrationUrl: 'https://wingbits.com/',
    docsUrl: 'https://wingbits.com/docs',
    envKey: 'WINGBITS_API_KEY',
    free: false,
    rateLimit: 'Paid subscription',
    status: 'premium',
  },

  // ADDITIONAL MARITIME
  {
    id: 'corridor_risk',
    name: 'CorridorRisk',
    category: 'Maritime',
    description: 'Maritime corridor risk scoring',
    registrationUrl: 'https://corridorrisk.io/',
    docsUrl: 'https://corridorrisk.io/docs',
    envKey: 'CORRIDOR_RISK_API_KEY',
    free: false,
    rateLimit: 'Paid subscription',
    status: 'premium',
  },

  // ADDITIONAL WEATHER & DISASTER
  {
    id: 'nasa_firms_api',
    name: 'NASA FIRMS API Key',
    category: 'Weather & Disaster',
    description: 'Required for fire detection seeding (separate from map key)',
    registrationUrl: 'https://firms.modaps.eosdis.nasa.gov/api/',
    docsUrl: 'https://firms.modaps.eosdis.nasa.gov/mapserver/',
    envKey: 'NASA_FIRMS_API_KEY',
    free: true,
    rateLimit: 'Free public API',
    status: 'authenticated',
  },
  {
    id: 'openaq',
    name: 'OpenAQ',
    category: 'Weather & Disaster',
    description: 'Air quality data from 10,000+ stations worldwide',
    registrationUrl: 'https://docs.openaq.org/using-the-api/api-key',
    docsUrl: 'https://docs.openaq.org/',
    envKey: 'OPENAQ_API_KEY',
    free: true,
    rateLimit: 'Free tier available',
    status: 'authenticated',
  },
  {
    id: 'waqi',
    name: 'WAQI / World Air Quality Index',
    category: 'Weather & Disaster',
    description: 'Additional air quality station coverage',
    registrationUrl: 'https://aqicn.org/data-platform/token/',
    docsUrl: 'https://aqicn.org/api/',
    envKey: 'WAQI_API_KEY',
    free: true,
    rateLimit: 'Free with registration',
    status: 'authenticated',
  },
  {
    id: 'reliefweb',
    name: 'ReliefWeb',
    category: 'Weather & Disaster',
    description: 'Humanitarian disaster news and reports',
    registrationUrl: 'https://reliefweb.int/',
    docsUrl: 'https://reliefweb.int/help/api',
    envKey: 'RELIEFWEB_APPNAME',
    free: true,
    rateLimit: 'Free public API (requires app name)',
    status: 'authenticated',
  },
  {
    id: 'windy',
    name: 'Windy.com',
    category: 'Weather & Disaster',
    description: 'Webcam imagery and weather visualization',
    registrationUrl: 'https://api.windy.com/',
    docsUrl: 'https://api.windy.com/docs',
    envKey: 'WINDY_API_KEY',
    free: true,
    rateLimit: 'Free tier available',
    status: 'authenticated',
  },
  {
    id: 'cloudflare_radar',
    name: 'Cloudflare Radar',
    category: 'Weather & Disaster',
    description: 'Internet outage detection and network analytics',
    registrationUrl: 'https://radar.cloudflare.com/',
    docsUrl: 'https://developers.cloudflare.com/radar/',
    envKey: 'CLOUDFLARE_API_TOKEN',
    free: true,
    rateLimit: 'Free with Cloudflare account',
    status: 'authenticated',
  },

  // ADDITIONAL AI / ANALYTICS
  {
    id: 'groq',
    name: 'Groq',
    category: 'AI & Analytics',
    description: 'Fast AI inference (14,400 req/day free)',
    registrationUrl: 'https://console.groq.com/',
    docsUrl: 'https://console.groq.com/docs',
    envKey: 'GROQ_API_KEY',
    free: true,
    rateLimit: '14,400 req/day (free)',
    status: 'authenticated',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'AI & Analytics',
    description: 'Unified API for multiple LLMs (fallback)',
    registrationUrl: 'https://openrouter.ai/',
    docsUrl: 'https://openrouter.ai/docs',
    envKey: 'OPENROUTER_API_KEY',
    free: true,
    rateLimit: '50 req/day (free)',
    status: 'authenticated',
  },
  {
    id: 'ollama',
    name: 'Ollama (Local LLM)',
    category: 'AI & Analytics',
    description: 'Self-hosted LLM endpoint',
    registrationUrl: 'https://ollama.ai/',
    docsUrl: 'https://github.com/ollama/ollama/blob/main/docs/api.md',
    envKeys: ['OLLAMA_API_URL', 'OLLAMA_MODEL', 'OLLAMA_API_KEY'],
    free: true,
    rateLimit: 'Local hardware dependent',
    status: 'authenticated',
  },

  // ECONOMIC / FINANCIAL DATA
  {
    id: 'fred',
    name: 'FRED (Federal Reserve Economic Data)',
    category: 'Economic & Financial',
    description: 'US economic time series data',
    registrationUrl: 'https://fred.stlouisfed.org/docs/api/api_key.html',
    docsUrl: 'https://fred.stlouisfed.org/docs/api/',
    envKey: 'FRED_API_KEY',
    free: true,
    rateLimit: '120 req/min',
    status: 'authenticated',
  },
  {
    id: 'eia',
    name: 'EIA (Energy Information Administration)',
    category: 'Economic & Financial',
    description: 'US energy prices, production, inventory data',
    registrationUrl: 'https://www.eia.gov/opendata/',
    docsUrl: 'https://www.eia.gov/opendata/documentation.php',
    envKey: 'EIA_API_KEY',
    free: true,
    rateLimit: '5,000 req/day',
    status: 'authenticated',
  },
  {
    id: 'imf',
    name: 'IMF (International Monetary Fund)',
    category: 'Economic & Financial',
    description: 'WEO, gold reserves, national debt data',
    registrationUrl: 'https://portal.api.imf.org/',
    docsUrl: 'https://portal.api.imf.org/docs',
    envKey: 'IMF_API_KEY',
    free: true,
    rateLimit: 'Free with registration',
    status: 'authenticated',
  },
  {
    id: 'alphavantage',
    name: 'Alpha Vantage',
    category: 'Economic & Financial',
    description: 'Stock and commodity quotes (fallback)',
    registrationUrl: 'https://www.alphavantage.co/support/#api-key',
    docsUrl: 'https://www.alphavantage.co/documentation/',
    envKey: 'ALPHA_VANTAGE_API_KEY',
    free: true,
    rateLimit: '25 req/day (free), 500 req/day (premium)',
    status: 'authenticated',
  },
  {
    id: 'coingecko',
    name: 'CoinGecko',
    category: 'Economic & Financial',
    description: 'Cryptocurrency market data',
    registrationUrl: 'https://www.coingecko.com/en/api',
    docsUrl: 'https://www.coingecko.com/en/api/documentation',
    envKeys: ['COINGECKO_API_KEY', 'COINGECKO_DEMO_API_KEY'],
    free: true,
    rateLimit: 'Demo: 10-50 req/min, Pro: higher',
    status: 'authenticated',
  },
  {
    id: 'gie',
    name: 'GIE AGSI+',
    category: 'Economic & Financial',
    description: 'European gas storage levels',
    registrationUrl: 'https://agsi.gie.eu/account',
    docsUrl: 'https://agsi.gie.eu/api',
    envKey: 'GIE_API_KEY',
    free: true,
    rateLimit: 'Free with registration',
    status: 'authenticated',
  },
  {
    id: 'entsoe',
    name: 'ENTSO-E Transparency Platform',
    category: 'Economic & Financial',
    description: 'EU electricity prices and load data',
    registrationUrl: 'https://transparency.entsoe.eu/',
    docsUrl: 'https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html',
    envKey: 'ENTSOE_E_TOKEN',
    free: true,
    rateLimit: 'Free with registration',
    status: 'authenticated',
  },
  {
    id: 'comtrade',
    name: 'UN Comtrade',
    category: 'Economic & Financial',
    description: 'Bilateral trade flows and import-HHI data',
    registrationUrl: 'https://comtradedeveloper.un.org/',
    docsUrl: 'https://comtradedeveloper.un.org/docs',
    envKey: 'COMTRADE_API_KEYS',
    free: true,
    rateLimit: '100 req/day per key (comma-separated keys)',
    status: 'authenticated',
  },
  {
    id: 'wto',
    name: 'WTO Trade Statistics',
    category: 'Economic & Financial',
    description: 'Tariff and trade statistics',
    registrationUrl: 'https://apiportal.wto.org/',
    docsUrl: 'https://apiportal.wto.org/',
    envKey: 'WTO_API_KEY',
    free: false,
    rateLimit: 'Paid subscription',
    status: 'premium',
  },

  // CYBER THREAT INTELLIGENCE
  {
    id: 'abuseipdb',
    name: 'AbuseIPDB',
    category: 'Cyber Threat Intelligence',
    description: 'IP reputation and abuse reporting',
    registrationUrl: 'https://www.abuseipdb.com/account/api',
    docsUrl: 'https://www.abuseipdb.com/api.html',
    envKey: 'ABUSEIPDB_API_KEY',
    free: true,
    rateLimit: '1,000 req/day (free)',
    status: 'authenticated',
  },
  {
    id: 'otx',
    name: 'AlienVault OTX',
    category: 'Cyber Threat Intelligence',
    description: 'Open threat exchange pulses',
    registrationUrl: 'https://otx.alienvault.com/api',
    docsUrl: 'https://otx.alienvault.com/api',
    envKey: 'OTX_API_KEY',
    free: true,
    rateLimit: 'Free with registration',
    status: 'authenticated',
  },
  {
    id: 'urlhaus',
    name: 'URLhaus (abuse.ch)',
    category: 'Cyber Threat Intelligence',
    description: 'Malicious URL feed',
    registrationUrl: 'https://urlhaus.abuse.ch/',
    docsUrl: 'https://urlhaus.abuse.ch/api/',
    envKey: 'URLHAUS_AUTH_KEY',
    free: true,
    rateLimit: 'Free with registration',
    status: 'authenticated',
  },

  // SEARCH / SCRAPING
  {
    id: 'exa',
    name: 'Exa Neural Search',
    category: 'Search & Scraping',
    description: 'Neural search for price discovery and research',
    registrationUrl: 'https://exa.ai/',
    docsUrl: 'https://docs.exa.ai/',
    envKey: 'EXA_API_KEYS',
    free: true,
    rateLimit: 'Free tier available',
    status: 'authenticated',
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    category: 'Search & Scraping',
    description: 'Web page scraping and content extraction',
    registrationUrl: 'https://www.firecrawl.dev/',
    docsUrl: 'https://docs.firecrawl.dev/',
    envKey: 'FIRECRAWL_API_KEY',
    free: true,
    rateLimit: 'Free tier available',
    status: 'authenticated',
  },
  {
    id: 'brave_search',
    name: 'Brave Search',
    category: 'Search & Scraping',
    description: 'Web search API',
    registrationUrl: 'https://brave.com/search/api/',
    docsUrl: 'https://api.search.brave.com/',
    envKey: 'BRAVE_API_KEYS',
    free: true,
    rateLimit: '2,000 req/mo (free)',
    status: 'authenticated',
  },

  // NOTIFICATIONS
  {
    id: 'telegram_bot',
    name: 'Telegram Bot',
    category: 'Notifications',
    description: 'Push notifications via Telegram',
    registrationUrl: 'https://core.telegram.org/bots',
    docsUrl: 'https://core.telegram.org/bots/api',
    envKeys: ['TELEGRAM_BOT_TOKEN', 'TELEGRAM_WEBHOOK_SECRET'],
    free: true,
    rateLimit: '30 msg/sec per bot',
    status: 'authenticated',
  },
  {
    id: 'resend',
    name: 'Resend',
    category: 'Notifications',
    description: 'Email notification delivery',
    registrationUrl: 'https://resend.com/',
    docsUrl: 'https://resend.com/docs',
    envKeys: ['RESEND_API_KEY', 'RESEND_FROM_EMAIL', 'RESEND_FROM_BRIEF'],
    free: true,
    rateLimit: '100 emails/day (free)',
    status: 'authenticated',
  },
  {
    id: 'discord_oauth',
    name: 'Discord OAuth',
    category: 'Notifications',
    description: 'Discord webhook notifications',
    registrationUrl: 'https://discord.com/developers/applications',
    docsUrl: 'https://discord.com/developers/docs',
    envKeys: ['DISCORD_CLIENT_ID', 'DISCORD_CLIENT_SECRET', 'DISCORD_REDIRECT_URI'],
    free: true,
    rateLimit: 'Standard Discord API limits',
    status: 'authenticated',
  },
  {
    id: 'slack_oauth',
    name: 'Slack OAuth',
    category: 'Notifications',
    description: 'Slack workspace notifications',
    registrationUrl: 'https://api.slack.com/apps',
    docsUrl: 'https://api.slack.com/docs',
    envKeys: ['SLACK_CLIENT_ID', 'SLACK_CLIENT_SECRET', 'SLACK_REDIRECT_URI'],
    free: true,
    rateLimit: 'Standard Slack API limits',
    status: 'authenticated',
  },
  {
    id: 'vapid',
    name: 'Web Push (VAPID)',
    category: 'Notifications',
    description: 'Browser push notifications',
    registrationUrl: 'https://web-push-codelab.glitch.me/',
    docsUrl: 'https://github.com/web-push-libs/web-push',
    envKeys: ['VAPID_PUBLIC_KEY', 'VAPID_PRIVATE_KEY', 'VAPID_SUBJECT'],
    free: true,
    rateLimit: 'Depends on push service',
    status: 'authenticated',
  },

  // AUTH & SECURITY
  {
    id: 'clerk',
    name: 'Clerk Auth',
    category: 'Auth & Security',
    description: 'User authentication and management',
    registrationUrl: 'https://clerk.com/',
    docsUrl: 'https://clerk.com/docs',
    envKeys: ['CLERK_SECRET_KEY', 'CLERK_JWT_ISSUER_DOMAIN'],
    free: true,
    rateLimit: '10,000 MAU (free)',
    status: 'authenticated',
  },
  {
    id: 'turnstile',
    name: 'Cloudflare Turnstile',
    category: 'Auth & Security',
    description: 'CAPTCHA verification',
    registrationUrl: 'https://dash.cloudflare.com/?to=/:account/turnstile',
    docsUrl: 'https://developers.cloudflare.com/turnstile/',
    envKey: 'TURNSTILE_SECRET_KEY',
    free: true,
    rateLimit: 'Free tier available',
    status: 'authenticated',
  },
  {
    id: 'wm_session',
    name: 'WorldMonitor Session',
    category: 'Auth & Security',
    description: 'Session cookie signing secret',
    registrationUrl: '',
    docsUrl: '',
    envKey: 'WM_SESSION_SECRET',
    free: true,
    rateLimit: 'Internal use',
    status: 'authenticated',
  },

  // PAYMENTS
  {
    id: 'dodo_payments',
    name: 'Dodo Payments',
    category: 'Payments',
    description: 'Subscription billing and checkout',
    registrationUrl: 'https://app.dodopayments.com/',
    docsUrl: 'https://docs.dodopayments.com/',
    envKeys: ['DODO_API_KEY', 'DODO_WEBHOOK_SECRET', 'DODO_IDENTITY_SIGNING_SECRET', 'DODO_BUSINESS_ID'],
    free: false,
    rateLimit: 'Per plan',
    status: 'premium',
  },

  // INFRASTRUCTURE
  {
    id: 'upstash_redis',
    name: 'Upstash Redis',
    category: 'Infrastructure',
    description: 'Serverless Redis for caching',
    registrationUrl: 'https://upstash.com/',
    docsUrl: 'https://docs.upstash.com/',
    envKeys: ['UPSTASH_REDIS_REST_URL', 'UPSTASH_REDIS_REST_TOKEN'],
    free: true,
    rateLimit: '10k req/day (free)',
    status: 'authenticated',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'Infrastructure',
    description: 'PostgreSQL database and auth',
    registrationUrl: 'https://supabase.com/',
    docsUrl: 'https://supabase.com/docs',
    envKeys: ['SUPABASE_URL', 'SUPABASE_ANON_KEY'],
    free: true,
    rateLimit: 'Free tier: 500MB DB',
    status: 'authenticated',
  },
  {
    id: 'cloudflare_r2',
    name: 'Cloudflare R2',
    category: 'Infrastructure',
    description: 'S3-compatible object storage',
    registrationUrl: 'https://dash.cloudflare.com/',
    docsUrl: 'https://developers.cloudflare.com/r2/',
    envKeys: ['CLOUDFLARE_R2_ACCOUNT_ID', 'CLOUDFLARE_R2_BUCKET', 'CLOUDFLARE_R2_ACCESS_KEY_ID', 'CLOUDFLARE_R2_SECRET_ACCESS_KEY'],
    free: true,
    rateLimit: '10GB/mo free',
    status: 'authenticated',
  },

  // CONVEX
  {
    id: 'convex',
    name: 'Convex',
    category: 'Infrastructure',
    description: 'Real-time database for auth/payments',
    registrationUrl: 'https://convex.dev/',
    docsUrl: 'https://docs.convex.dev/',
    envKeys: ['CONVEX_URL', 'CONVEX_SITE_URL', 'CONVEX_SERVER_SHARED_SECRET'],
    free: true,
    rateLimit: 'Free tier available',
    status: 'authenticated',
  },

  // ── CONFLICT & GEOPOLITICS ──
  {
    id: 'ucdp',
    name: 'UCDP (Uppsala Conflict Data Program)',
    category: 'Conflict & Geopolitics',
    description: 'Armed conflict events — battles, one-sided violence, dyadic state-based',
    registrationUrl: 'https://ucdp.uu.se/downloads/',
    docsUrl: 'https://ucdpapi.pcr.uu.se/',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },
  {
    id: 'acled',
    name: 'ACLED (Armed Conflict Location & Event Data)',
    category: 'Conflict & Geopolitics',
    description: 'Real-time conflict and protest data — granular event-level coverage',
    registrationUrl: 'https://acleddata.com/',
    docsUrl: 'https://acleddata.com/data-export-tool/',
    envKey: 'ACLED_API_KEY',
    free: true,
    rateLimit: 'Free with registration',
    status: 'authenticated',
  },

  // ── SANCTIONS ──
  {
    id: 'ofac_sdn',
    name: 'OFAC SDN List',
    category: 'Sanctions',
    description: 'US Treasury Specially Designated Nationals list — sanctioned entities',
    registrationUrl: 'https://www.treasury.gov/ofac/',
    docsUrl: 'https://www.treasury.gov/resource-center/sanctions/SDN-List/',
    free: true,
    rateLimit: 'Free public data',
    status: 'public',
  },
  {
    id: 'open_sanctions',
    name: 'OpenSanctions',
    category: 'Sanctions',
    description: 'Aggregated sanctions and PEP data — 90+ lists in unified API',
    registrationUrl: 'https://opensanctions.org/',
    docsUrl: 'https://docs.opensanctions.org/',
    free: true,
    rateLimit: 'Free tier available',
    status: 'authenticated',
  },

  // (gpsjam removed — no public machine-readable feed)

  // ── CLIMATE & ENVIRONMENT ──
  {
    id: 'noaa_climate',
    name: 'NOAA Climate Data',
    category: 'Weather & Disaster',
    description: 'Global temperature anomalies, CO2 monitoring, sea ice extent',
    registrationUrl: 'https://www.ncdc.noaa.gov/',
    docsUrl: 'https://www.ncei.noaa.gov/',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },
  {
    id: 'nsidc',
    name: 'NSIDC Sea Ice',
    category: 'Weather & Disaster',
    description: 'National Snow and Ice Data Center — Arctic/Antarctic sea ice extent',
    registrationUrl: 'https://nsidc.org/',
    docsUrl: 'https://nsidc.org/data',
    free: true,
    rateLimit: 'Free public data',
    status: 'public',
  },
  {
    id: 'who_air_quality',
    name: 'WHO Air Quality',
    category: 'Health',
    description: 'World Health Organization air quality indicators — PM2.5, AQI',
    registrationUrl: 'https://www.who.int/',
    docsUrl: 'https://www.who.int/data/gho',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },

  // ── DISPLACEMENT ──
  {
    id: 'unhcr',
    name: 'UNHCR Population Data',
    category: 'Displacement',
    description: 'UN refugee agency — displaced populations by country and type',
    registrationUrl: 'https://www.unhcr.org/',
    docsUrl: 'https://www.unhcr.org/en-us/data',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },

  // ── ENERGY & RESOURCES ──
  {
    id: 'gie_agsi',
    name: 'GIE AGSI (Gas Storage)',
    category: 'Economic & Financial',
    description: 'Gas Infrastructure Europe — underground gas storage fill levels',
    registrationUrl: 'https://agsi.gie.eu/',
    docsUrl: 'https://agsi.gie.eu/api',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },

  // ── MARKETS ──
  {
    id: 'polymarket',
    name: 'Polymarket',
    category: 'Economic & Financial',
    description: 'Prediction market odds — geopolitical and economic event probabilities',
    registrationUrl: 'https://polymarket.com/',
    docsUrl: 'https://docs.polymarket.com/',
    free: true,
    rateLimit: 'Free public API',
    status: 'public',
  },
  {
    id: 'goldapi',
    name: 'Gold Price API',
    category: 'Economic & Financial',
    description: 'Real-time gold, silver, platinum prices — safe haven indicators',
    registrationUrl: 'https://www.goldapi.io/',
    docsUrl: 'https://www.goldapi.io/documentation',
    envKey: 'GOLDAPI_API_KEY',
    free: true,
    rateLimit: '100 req/day free',
    status: 'authenticated',
  },
];



export function getCategories(): string[] {
  return Array.from(new Set(API_METADATA.map((api) => api.category)));
}

