"""
Terranoetis — Tsunami Wave Propagation Simulation
2D shallow water equations (continuity + momentum) on ocean bathymetry,
solved with a Lax-Friedrichs finite-difference scheme.

Physics:
  - Continuity:   ∂η/∂t + ∇·(H·u) = 0          (H = still-water depth + η)
  - Momentum:     ∂u/∂t + ··· = -g·∇η   (long-wave gravity restoring force)
  - Wave speed:   c = sqrt(g·H)                  (real shallow-water celerity)
  - Initial source: simplified Okada-style elastic dislocation uplift —
    vertical seafloor displacement from finite-fault slip transferred to
    the water surface (Okada 1985 in spirit; here a rectangular fault
    patch with dip-slip, azimuthal lobes, and moment-magnitude scaling).

Author: Terranoetis / Freebuff
"""

import json, os, time, traceback
import numpy as np

# ── JSON-safe conversion ───────────────────────────────────────────
# NumPy 2.x scalars (np.bool_, np.float64, np.int64, ...) are no longer
# subclasses of Python's bool/float/int, so json.dump/dumps on a dict that
# contains one raises `TypeError: Object of type bool is not JSON serializable`
# (observed on Kaggle). Recursively convert every numpy scalar/array to native
# Python types so result serialization is numpy-version-agnostic.
def _json_safe(obj):
    if isinstance(obj, np.ndarray):
        if obj.ndim == 0:
            return _json_safe(obj.item())
        return [_json_safe(v) for v in obj.tolist()]
    if isinstance(obj, np.generic):
        obj = obj.item()
    if isinstance(obj, float):
        if obj != obj or obj in (float('inf'), float('-inf')):
            return None
        return obj
    if isinstance(obj, dict):
        return {k: _json_safe(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_json_safe(v) for v in obj]
    return obj

from swe_solver import run_tsunami, verify_closed_box

def generate_bathymetry(N):
    """Generate synthetic ocean bathymetry (depth in meters, positive down).
    Fallback only — real GEBCO 2020 bathymetry (bathy_b64) is preferred."""
    y, x = np.meshgrid(np.linspace(-1, 1, N), np.linspace(-1, 1, N))
    # Deep ocean in center, shallower at edges (coast)
    bathy = 4000 * (1 - 0.3 * (x**2 + y**2))
    bathy += np.random.randn(N, N).astype(np.float64) * 100
    return np.clip(bathy, 50, 6000)


def _bilinear_upsample(src, src_n, out_n):
    """
    Bilinearly upsample a square [src_n, src_n] elevation grid to
    [out_n, out_n]. Used to lift a coarse server-sampled GEBCO bathymetry
    (e.g. 64x64) to the simulation resolution (e.g. 256x256).
    Row 0 is the north edge for both grids, matching the renderer.
    """
    src = np.asarray(src, dtype=np.float64)
    s = np.arange(out_n) * (src_n - 1) / max(1, out_n - 1)
    y0 = np.clip(s.astype(int), 0, src_n - 2)
    y1 = y0 + 1
    fy = s - y0
    x0 = np.clip(s.astype(int), 0, src_n - 2)
    x1 = x0 + 1
    fx = s - x0
    out = np.empty((out_n, out_n), dtype=np.float64)
    for j in range(out_n):
        out[j] = (src[y0[j], x0] * (1 - fy[j]) * (1 - fx)
                  + src[y0[j], x1] * (1 - fy[j]) * fx
                  + src[y1[j], x0] * fy[j] * (1 - fx)
                  + src[y1[j], x1] * fy[j] * fx)
    return out

def _place_source_in_deep_ocean(bathy, gs):
    """
    Find the offshore source location for the tsunami.

    A tsunami is generated by a seafloor rupture IN THE DEEP OCEAN, tens to
    hundreds of km from shore, not at the box center (which is usually the
    drawn city = land). We locate the deep-water region of the box and return
    its depth-weighted centroid, snapped onto an ocean cell. This pulls the
    fault seaward of the coast so the wave propagates from deep water → shelf
    → shore (generation → shoaling → runup).

    Returns (cy, cx) in grid cells (floats), plus the number of ocean cells.
    Falls back to the box centre when the box has no ocean (the wave will be
    weak, and the client validation should have rejected this box anyway).
    """
    is_ocean = bathy > 50.0
    n_ocean = int(is_ocean.sum())
    if n_ocean == 0:
        return gs // 2, gs // 2, 0
    yy, xx = np.meshgrid(np.arange(gs), np.arange(gs), indexing='ij')
    w = np.where(is_ocean, np.maximum(bathy, 0.0), 0.0)
    total = w.sum()
    if total <= 0:
        return gs // 2, gs // 2, n_ocean
    cy = float((yy * w).sum() / total)
    cx = float((xx * w).sum() / total)
    return cy, cx, n_ocean


def _station_series_from_snapshots(snapshots, row, col):
    times = np.array([snap['time_minutes'] for snap in snapshots], dtype=np.float64)
    values = np.array([float(snap['water_height'][row, col]) for snap in snapshots], dtype=np.float64)
    return times, values


def _arrival_time(times, values, threshold_m):
    for idx in range(len(values)):
        if abs(values[idx]) >= threshold_m:
            return float(times[idx])
    return None


def _benchmark_station_report(snapshots, stations):
    if not stations:
        return {'enabled': False, 'stations': []}

    if not snapshots:
        return {'enabled': True, 'station_count': len(stations), 'valid_station_count': 0, 'stations': [], 'mean_nrmse': None, 'mean_abs_arrival_error_min': None, 'notes': ['No snapshots available for benchmark comparison.']}

    grid_rows, grid_cols = snapshots[0]['water_height'].shape

    summary = []
    for station in stations:
        name = str(station.get('name', 'station'))
        row = int(np.clip(int(station.get('row', 0)), 0, grid_rows - 1))
        col = int(np.clip(int(station.get('col', 0)), 0, grid_cols - 1))
        obs_t = np.asarray(station.get('observed_times_min', []), dtype=np.float64)
        obs_eta = np.asarray(station.get('observed_eta_m', []), dtype=np.float64)
        if obs_t.size == 0 or obs_eta.size == 0 or obs_t.size != obs_eta.size:
            summary.append({
                'name': name,
                'status': 'invalid-observation-series',
            })
            continue

        model_t, model_eta = _station_series_from_snapshots(snapshots, row, col)
        model_interp = np.interp(obs_t, model_t, model_eta)
        rmse = float(np.sqrt(np.mean((model_interp - obs_eta) ** 2)))
        denom = float(np.sqrt(np.mean(obs_eta ** 2)))
        nrmse = float(rmse / denom) if denom > 1e-12 else rmse
        peak_obs_idx = int(np.argmax(np.abs(obs_eta)))
        peak_mod_idx = int(np.argmax(np.abs(model_interp)))
        peak_error_m = float(np.max(np.abs(model_interp)) - np.max(np.abs(obs_eta)))
        threshold = float(station.get('arrival_threshold_m', max(0.05, 0.1 * np.max(np.abs(obs_eta)))))
        arrival_obs = _arrival_time(obs_t, obs_eta, threshold)
        arrival_model = _arrival_time(obs_t, model_interp, threshold)
        if arrival_obs is not None and arrival_model is not None:
            arrival_error_min = float(arrival_model - arrival_obs)
        else:
            arrival_error_min = None
        summary.append({
            'name': name,
            'row': row,
            'col': col,
            'threshold_m': threshold,
            'rmse_m': rmse,
            'nrmse': nrmse,
            'peak_error_m': peak_error_m,
            'arrival_time_error_min': arrival_error_min,
            'status': 'ok',
        })

    valid = [s for s in summary if s.get('status') == 'ok']
    arrival_errors = [abs(s['arrival_time_error_min']) for s in valid if s['arrival_time_error_min'] is not None]
    overall = {
        'enabled': True,
        'station_count': len(summary),
        'valid_station_count': len(valid),
        'stations': summary,
        'mean_nrmse': float(np.mean([s['nrmse'] for s in valid])) if valid else None,
        'mean_abs_arrival_error_min': float(np.mean(arrival_errors)) if arrival_errors else None,
        'notes': [
            'Observations are compared only at supplied station cells.',
            'This is an offline benchmark layer; it does not fetch NOAA data automatically yet.',
        ],
    }
    return overall


def simulate_tsunami(params):
    t0 = time.time()
    gs = int(params.get('grid_size', 256))
    magnitude = float(params.get('magnitude', 8.5))
    displace_m = float(params.get('seafloor_displacement_m', 5))
    duration_min = float(params.get('duration_minutes', 30))
    lat = float(params.get('lat', 35.0))
    lon = float(params.get('lon', 140.0))

    print(f"\n{'='*60}")
    print("TERRANOETIS — TSUNAMI WAVE PROPAGATION")
    print(f"{'='*60}")
    print(f"M{magnitude:.1f} source | displacement={displace_m}m | grid={gs}x{gs}")

    # ── Bathymetry: real GEBCO 2020 grid (bathy_b64) or synthetic bowl ──
    # simRunner embeds a uint16 min/span-quantized positive-down depth grid
    # sampled at ~64x64; we decode it and bilinearly upsample to gs. Land
    # cells carry negative depth (elevation above sea level), deep ocean
    # carries large positive depth — this is what steers c = sqrt(g·H) and
    # shoaling/runup in the shallow-water integration.
    bathy_gs0 = int(params.get('bathy_gs', 0) or 0)
    bathy_b64 = params.get('bathy_b64')
    use_real_bathy = bool(bathy_gs0 > 1)
    if use_real_bathy and bathy_b64:
        try:
            import base64
            raw = base64.b64decode(bathy_b64)
            u16 = np.frombuffer(raw, dtype='<u2')
            if len(u16) == bathy_gs0 * bathy_gs0:
                bmin = float(params.get('bathy_min', 0.0))
                bspan = float(params.get('bathy_span', 1.0))
                flat = bmin + (u16 / 65534.0) * bspan
                bathy_2d = np.asarray(flat, dtype=np.float64).reshape(bathy_gs0, bathy_gs0)
                bathy = _bilinear_upsample(bathy_2d, bathy_gs0, gs)
                print(f"[BATHYMETRY] Real GEBCO 2020 {bathy_gs0}x{bathy_gs0} -> {gs}x{gs}")
            else:
                use_real_bathy = False
        except Exception:
            use_real_bathy = False
    if not use_real_bathy:
        raise RuntimeError(
            'Real GEBCO bathymetry is required for tsunami simulations; synthetic fallback is disabled.'
        )

    g = 9.81
    extent_km = float(params.get('extent_km', 0.0))
    dx = (extent_km * 1000.0 / gs) if extent_km > 0 else 5000.0  # 5 km cells
    # CFL-compliant timestep from the physical long-wave celerity sqrt(g·Hmax):
    #   dt = 0.9 · dx / (sqrt(2) · c_max);  2D LF needs √2·c·dt/dx ≤ ~1.
    _c_max0 = np.sqrt(g * max(np.max(bathy), 1.0))
    dt = float(params.get('dt_s', 0.9 * dx / (np.sqrt(2.0) * _c_max0)))

    # h represents free-surface elevation above still-water level (η)
    # Still-water depth: bathy is positive-down so ocean depth B = +bathy.
    # Total water column H = B + η.

    # ── Initial condition: Okada (1985)-style finite-fault dislocation ──
    # A rectangular dip-slip rupture: elliptical slip patch with uplift on
    # the hanging-wall side and subsidence on the footwall side, vertical
    # seafloor displacement transferred 1:1 to the free surface.
    # Amplitude scales with seismic moment M0 = 10^(1.5·M + 9.1).
    #
    # SOURCE PLACEMENT: a tsunami is generated at sea — an offshore megathrust
    # rupture, not at the drawn box's centre (usually the city = land). We
    # centre the fault at the deep-ocean region of the box so the wave starts
    # offshore and propagates toward the coast (generation → shoaling → runup).
    is_ocean = bathy > 50.0
    cy, cx, n_ocean = _place_source_in_deep_ocean(bathy, gs)
    print(f"[SOURCE] offshore rupture at cell ({cx:.1f},{cy:.1f}) "
          f"| deep-ocean cells={n_ocean}/{gs*gs}")
    y, x = np.meshgrid(np.arange(gs), np.arange(gs), indexing='ij')

    strike_deg = float(params.get('rupture_strike_deg', 135.0))
    # Seismic moment (N·m) and moment ratio relative to a reference Mw 8.0
    M0 = 10.0 ** (1.5 * magnitude + 9.1)
    M0_ref = 10.0 ** (1.5 * 8.0 + 9.1)
    # Characteristic slip scales as sqrt(M0 ratio) for a fixed-fault-area source
    displace_amp = displace_m * np.sqrt(M0 / M0_ref) / 5.6  # normalized so
    # that seafloor_displacement_m ≈ max uplift at the *reference* magnitude

    # Fault-aligned coordinates (km): along-strike and along-dip
    th = np.radians(strike_deg)
    dxm = (x - cx) * dx            # meters
    dym = (y - cy) * dx
    along = (dxm * np.cos(th) + dym * np.sin(th)) / 1000.0     # km, strike
    across = (-dxm * np.sin(th) + dym * np.cos(th)) / 1000.0   # km, dip
    # Rupture dimensions grow with magnitude (Wells & Coppersmith style)
    half_len_km = 20.0 * 10.0 ** (0.5 * (magnitude - 8.0))     # ~20 km @ M8
    half_wid_km = max(half_len_km * 0.4, 8.0)
    # Clip each elliptical factor *before* multiplying so the patch is
    # bounded [0, 1] everywhere (do not clip the product — the product of
    # two large factors makes huge values when both |along|, |across| > 1).
    slip_along = np.clip(1.0 - (along / half_len_km) ** 2, 0.0, 1.0)
    slip_across = np.clip(1.0 - (across / half_wid_km) ** 2, 0.0, 1.0)
    slip_patch = slip_along * slip_across
    # Dip-slip asymmetry: uplift lobe (hanging wall) / subsidence (footwall)
    uplift_lobe = np.tanh(across / (0.5 * half_wid_km))

    # Displace the sea surface by the seafloor displacement (deep ocean only)
    h = np.where(is_ocean, displace_amp * slip_patch * uplift_lobe, 0.0)
    print(f"[OKADA] M0={M0:.2e} N·m | strike={strike_deg:.0f}° | "
          f"L={2*half_len_km:.0f}km W={2*half_wid_km:.0f}km | "
          f"max uplift={h.max():+.2f} m")

    B = np.maximum(bathy, 0.0)
    c_max = np.sqrt(g * max(B.max(), 1.0))
    cfl_wave = np.sqrt(2.0) * c_max * dt / dx
    print(f"[CFL] c_max={c_max:.0f} m/s | dt={dt}s dx={dx:.0f}m | "
          f"√2·c·dt/dx={cfl_wave:.2f} ({'OK' if cfl_wave <= 1.0 else 'UNSTABLE!'})")
    # The solver now lives in swe_solver.py; keep the kernel focused on I/O.
    h0 = np.where(is_ocean, displace_amp * slip_patch * uplift_lobe, 0.0)
    h, hu, hv, solver_snapshots = run_tsunami(
        h0=h0,
        bathymetry=B,
        duration_s=duration_min * 60.0,
        dx=dx,
        dy=dx,
        dt=dt,
        g=g,
        manning_n=0.03,
        snapshot_count=20,
    )
    snapshots = [
        {'water_height': snap.water_height,
         'time_minutes': snap.time_minutes,
         'wave_height_m': snap.wave_height_m,
         'propagation_speed_ms': snap.propagation_speed_ms}
        for snap in solver_snapshots
    ]
    elapsed = time.time() - t0
    cell_area = dx * dx
    initial_depth = np.maximum(B + h0, 0.0)
    final_depth = np.maximum(B + h, 0.0)
    initial_volume_m3 = float(np.sum(initial_depth) * cell_area)
    final_volume_m3 = float(np.sum(final_depth) * cell_area)
    volume_drift_m3 = float(final_volume_m3 - initial_volume_m3)
    relative_volume_drift_pct = float((volume_drift_m3 / initial_volume_m3) * 100.0) if initial_volume_m3 > 0 else 0.0
    wet_fraction = float(np.mean(final_depth > 1e-6))
    final_speed = float(np.max(np.sqrt(hu**2 + hv**2) / np.maximum(final_depth, 1e-8)))
    validation = {
        'initial_volume_m3': initial_volume_m3,
        'final_volume_m3': final_volume_m3,
        'volume_drift_m3': volume_drift_m3,
        'relative_volume_drift_pct': relative_volume_drift_pct,
        'peak_wave_height_m': float(np.max(np.abs(h))),
        'max_speed_ms': final_speed,
        'wet_fraction': wet_fraction,
        'snapshot_count': len(snapshots),
        'solver': 'finite_volume_swe_hll_minmod',
        'validation_notes': [
            'No synthetic bathymetry fallback was used.',
            'This report is an internal conservation diagnostic, not a NOAA benchmark comparison.',
        ],
    }

    # Potential energy  ½·g·η²·cell_area  +  kinetic  ½·H·|u|²·cell_area
    H_final = np.maximum(B + h, 0.1)
    pe = np.sum(0.5 * g * h**2) * dx**2
    ke = np.sum(0.5 * H_final * ((hu**2 + hv**2) / H_final**2)) * dx**2
    final = {'water_height': h.astype(np.float32), 'bathymetry': bathy.astype(np.float32),
             'max_wave_height': float(np.max(np.abs(h))),
             'total_energy': float(pe + ke),
             'potential_energy_J': float(pe), 'kinetic_energy_J': float(ke),
             'c_max_longwave_ms': float(np.sqrt(g * max(B.max(), 1.0)))}
    benchmark = _benchmark_station_report(snapshots, params.get('benchmark_stations'))
    print(f"\n[DONE] {elapsed:.1f}s | max_wave={final['max_wave_height']:.2f}m | "
          f"E={final['total_energy']/1e9:.2f} GJ")
    return {'final': final, 'snapshots': snapshots,
            'params': {'grid_size': gs, 'magnitude': magnitude, 'seafloor_displacement_m': displace_m,
                       'duration_minutes': duration_min, 'lat': lat, 'lon': lon,
                       'cell_size_m': dx},
            'validation': validation,
            'benchmark': benchmark,
            'metadata': {'elapsed_seconds': elapsed, 'num_snapshots': len(snapshots),
                         'model': 'finite_volume_shallow_water_equations',
                         'source_model': 'okada_finite_fault_dislocation',
                         'wave_speed_formula': 'sqrt(g*H)'}}


# simRunner injects the run's JSON params here at push time (Kaggle only
# uploads the code file, so params cannot be passed as a sibling file).
EMBEDDED_PARAMS = None

def _load_params():
    """Load params from EMBEDDED_PARAMS (injected into main.py at push time)
    or from params.json anywhere on the runner."""
    if EMBEDDED_PARAMS:
        try:
            if isinstance(EMBEDDED_PARAMS, dict):
                return EMBEDDED_PARAMS
            return json.loads(EMBEDDED_PARAMS)
        except Exception:
            pass
    candidates = ['params.json', '/kaggle/working/params.json', '/kaggle/input/params.json']
    src = '/kaggle/src'
    if os.path.isdir(src):
        for root, _dirs, files in os.walk(src):
            if 'params.json' in files:
                candidates.append(os.path.join(root, 'params.json'))
    for p in candidates:
        try:
            if os.path.exists(p):
                with open(p) as f:
                    return json.load(f)
        except Exception:
            continue
    return None


def main():
    print("=" * 60)
    print("TERRANOETIS — Kaggle Tsunami Wave Propagation Simulation")
    print("=" * 60)
    params = _load_params()
    if params is not None:
        print(f"[PARAMS] Loaded: {json.dumps(_json_safe(params), indent=2)}")
    else:
        params = {'grid_size': 256, 'magnitude': 8.5, 'seafloor_displacement_m': 5,
                  'duration_minutes': 30, 'lat': 35.0, 'lon': 140.0}
    try:
        # ── Conservation proof: closed-box water volume conservation ──
        # Runs the same finite-volume HLL + minmod update loop on flat
        # bathymetry with a closed boundary and asserts Σ(bathymetry + h) is
        # conserved to machine precision. Fails the run if the solver is not
        # conservative.
        passed, _final, _init, _err = verify_closed_box(gs=64, steps=500, tol=1e-9)
        if not passed:
            raise RuntimeError(
                f"Tsunami solver failed closed-box conservation check (|Δ|={_err:.2e}). "
                "Refusing to run a non-conservative simulation."
            )

        result = simulate_tsunami(params)
        out = '/kaggle/working'; os.makedirs(out, exist_ok=True)
        np.save(f'{out}/water_height.npy', result['final']['water_height'])
        np.save(f'{out}/bathymetry.npy', result['final']['bathymetry'])
        if result['snapshots']:
            snap_d = np.stack([s['water_height'] for s in result['snapshots']])
            np.save(f'{out}/snapshots_height.npy', snap_d)
            np.save(f'{out}/snapshot_times.npy', np.array([s['time_minutes'] for s in result['snapshots']]))
        else:
            np.save(f'{out}/snapshots_height.npy', np.expand_dims(result['final']['water_height'], axis=0))
            np.save(f'{out}/snapshot_times.npy', np.array([0.0]))
        meta = {'params': result['params'], 'metadata': result['metadata'],
                'final_stats': {'max_wave_height': result['final']['max_wave_height'],
                                'total_energy': result['final']['total_energy']},
            'snapshot_count': len(result['snapshots']),
            'validation': result['validation'],
            'benchmark': result['benchmark']}
        with open(f'{out}/metadata.json', 'w') as f: json.dump(_json_safe(meta), f, indent=2)
        with open(f'{out}/validation.json', 'w') as f: json.dump(_json_safe(result['validation']), f, indent=2)
        with open(f'{out}/benchmark.json', 'w') as f: json.dump(_json_safe(result['benchmark']), f, indent=2)
        print(f"\n{'='*60}\nSIMULATION COMPLETE\n{'='*60}")
    except Exception as e:
        print(f"\n[ERROR] {e}"); traceback.print_exc()
        with open('/kaggle/working/error.log', 'w') as f: traceback.print_exc(file=f)
        raise

if __name__ == '__main__':
    main()
